name: Build
on:
  pull_request:
    branches: main
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
  
      - name: Install dependencies
        run: npm install
          
      # Runs tsc, eslint, and vite build
      - name: Build project 🔧
        run: npm run build 
